- Generally ML models Developed by maths

- Convert categoraical columns to Numerical columns

- Here we transform the data 

- This method is called as **Encoding**

- Feature Analysis:- first 5 sessions

- Feature Engineering:-Transform the data

- Feature selection:- Machine learning

- Before Model Development

- We will do EDA: Exploratory data analysis

    - Features(columns) analysis
    
        - Categorical ,Numerical,Outlier Analysis,Bivariate,MultiVariate
    
        - we will get insights
    
    - Feature Engineering
    
        - we will modify the data 
    
        - Models developed by maths
    
        - Encoding: Convert categorical data numerical data 
    
        - Scaling: All the numerical columns makes under one scales
    
        - Transformations: All the maths developed by assumptions data follows Normal distribution 
    
                        - convert skewed distribution to Normal
    - Feature Selection

- map  

- Label Encoder 

- OneHotEncoder

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

path='Visadataset.csv'
visa_df=pd.read_csv(path)
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [3]:
# check how many unique value available
visa_df["case_status"].unique()

array(['Denied', 'Certified'], dtype=object)

In [4]:
# Create a dictionary assign a number start with zero 
# for each lables based on alphabetic order 
d={"Certified":0,"Denied":1}
d

{'Certified': 0, 'Denied': 1}

In [6]:
# map the dict with column
visa_df["case_status"]=visa_df["case_status"].map(d)

In [7]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [ ]:
path='Visadataset.csv'
visa_df=pd.read_csv(path)



visa_df["case_status"].unique()

d={"Certified":0,"Denied":1}

visa_df["case_status"]=visa_df["case_status"].map(d)

In [8]:
visa_df["continent"].unique()

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [ ]:
d={"Africa":0,"Asia":1,"Europe":0,"North America":1,"Oceania":0,"South America":1}

In [12]:
d={}
d["asia"]=0
d["africa"]=1
d

{'asia': 0, 'africa': 1}

In [20]:
labels=sorted(visa_df["continent"].unique())
d={}
for i in range(len(labels)):
    key=labels[i]
    d[key]=i
d

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

**dictionary comprehension**

In [21]:
d={labels[i]:i for i in range(len(labels))}
d

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

In [30]:
path='Visadataset.csv'
visa_df=pd.read_csv(path)

for i in cat:
    labels=sorted(visa_df[i].unique())
    d={labels[i]:i for i in range(len(labels))}
    visa_df[i]=visa_df[i].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,0,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,1,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,2,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,3,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,4,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,17204,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,17205,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,17206,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,17207,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,17209,1,0,1,0,3195,1960,1,70876.9100,3,1,0

**Label Encoder**

package name : **sklearn**

    - class : **preprocessing**

        - method: **Label Encoder**

In [31]:
from sklearn.preprocessing import LabelEncoder

- step-1: import the  method 

- step-2: save the method 

- step-3: apply fit transform

In [37]:
from sklearn.preprocessing import LabelEncoder
path='Visadataset.csv'
visa_df=pd.read_csv(path)
le=LabelEncoder()
for i in cat:
    visa_df[i]=le.fit_transform(visa_df[i])

visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,0,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,1,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,2,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,3,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,4,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,17204,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,17205,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,17206,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,17207,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,17209,1,0,1,0,3195,1960,1,70876.9100,3,1,0

**One hot Encoder**

**pd.getdummies**

In [42]:
path='Visadataset.csv'
visa_df=pd.read_csv(path)

pd.get_dummies(visa_df["continent"],dtype="int")

       Africa  Asia  Europe  North America  Oceania  South America
0           0     1       0              0        0              0
1           0     1       0              0        0              0
2           0     1       0              0        0              0
3           0     1       0              0        0              0
4           1     0       0              0        0              0
...       ...   ...     ...            ...      ...            ...
25475       0     1       0              0        0              0
25476       0     1       0              0        0              0
25477       0     1       0              0        0              0
25478       0     1       0              0        0              0
25479       0     1       0              0        0              0

[25480 rows x 6 columns]

In [41]:
visa_df["continent"].values

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'], dtype=object)

**Label Encoder Vs OneHotEncoder**

- generally we dont want a relation between input column

- we need both input columns are not correlated to each other 

- we need both input columns are **independent(X,Y)** each other

- we need both input columns are **perpendicular** each other

- we need both input columns are **orthogonal** each other

- we need both input columns are **90 degree phase shift** each other

- OneHotEncoder will achive above

- But OneHotEncoder creates new columns

    - columns are increases means dimenssions are increases

    - More dimenssion data need more processing time

    - More dimenssion data need more infra

    - This is called Curse of dimensionality