In [1]:
import numpy as np 
import pandas as pd
Data={"Names":["Ramesh","Suresh","Sathish",np.nan],
     "Age":[np.nan,22,25,27],
     "City":["Pune","Pune",np.nan,"Hyd"]}
df=pd.DataFrame(Data)
df.to_csv("Dataframe.csv",index=False)
df

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [2]:
Data={"Names":["Ramesh","Suresh","Sathish",None],
     "Age":[None,22,25,27],
     "City":["Pune","Pune",None,"Hyd"]}
df1=pd.DataFrame(Data)
df1.to_csv("Dataframe1.csv",index=False)

In [3]:
Data={"Names":["Ramesh","Suresh","Sathish",Null],
     "Age":[Null,22,25,27],
     "City":["Pune","Pune",Null,"Hyd"]}
df2=pd.DataFrame(Data)
df2

NameError: name 'Null' is not defined

In [ ]:
# df DF1 both are same but nan is much better

In [4]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

In [5]:
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

In [6]:
df.isnull()

   Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [7]:
df.isnull().sum()
# column name age and city 1 1 1 missing values are there respectively

Names    1
Age      1
City     1
dtype: int64

In [8]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

**Method-1**

**Fill na**

In [9]:
df.fillna(30) # not recommended
# entier data frame will filled

     Names   Age  City
0   Ramesh  30.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0    30
3       30  27.0   Hyd

In [10]:
df["Age"].fillna(30)
# specific column will fill

0    30.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

- All the above one is we are filling randomly

- All the columns are filled with random number

- It is not a good approach beacause in a Data we have different Data types

**What is the difference between np.nan and None**

In [11]:
np.nan+5
# fill with value when column is Numerical

nan

In [12]:
None+5
# fill with character when column is Categorical

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [13]:
arr1=np.array([1,2,np.nan,3])
arr2=np.array([1,2,None,3])

In [14]:
arr1

array([ 1.,  2., nan,  3.])

In [15]:
arr2

array([1, 2, None, 3], dtype=object)

In [16]:
np.nansum(arr1),np.sum(arr1)

(np.float64(6.0), np.float64(nan))

In [17]:
np.sum(arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

- np.nan represents **float type**

- None represents **object**

- if data operations related to Maths then nan format is better

**Fill the value based on specific column**

In [18]:
df["Names"].fillna("Manish")

0     Ramesh
1     Suresh
2    Sathish
3     Manish
Name: Names, dtype: object

**Fill with methods**

- when ever we are using methods no need to provide values

$Methods Names$ 

- pad

- bfill

- ffill

- backfill

In [19]:
import warnings
warnings.filterwarnings("ignore")
df.fillna(method="pad")
# it is filling the values of specific coloumn with its is previous value

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [20]:
import warnings
warnings.filterwarnings("ignore")
df.fillna(method="pad",axis=1)
# it is filling the values of specific coloumn with its is previous value
# axis 1 means rows wise fill karta
# by default axis 0 columns wise fill karta

     Names     Age  City
0   Ramesh  Ramesh  Pune
1   Suresh    22.0  Pune
2  Sathish    25.0  25.0
3      NaN    27.0   Hyd

In [21]:
import warnings
warnings.filterwarnings("ignore")
df.fillna(method="bfill")
# it is fiiling the value based on the preceding value but in reverse direction

     Names   Age  City
0   Ramesh  22.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      NaN  27.0   Hyd

In [22]:
import warnings
warnings.filterwarnings("ignore")
df.fillna(method="ffill")
# it is filling the values of each column based on the preceding value but in forward direction
# it is same as pad

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [23]:
import warnings
warnings.filterwarnings("ignore")
df.fillna(method="backfill")
# it is same as bfill

     Names   Age  City
0   Ramesh  22.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      NaN  27.0   Hyd

**Fill with mean median mode**

- instead of filling with random values 

- we can use mean median and mode also 

- For numerical columns we mean and median

    - if Data has outlier then use median

- For categorical columns use mode

In [24]:
age_mean=df["Age"].mean()
df["Age"].fillna(age_mean)

0    24.666667
1    22.000000
2    25.000000
3    27.000000
Name: Age, dtype: float64

In [25]:
age_median=df["Age"].median()
df["Age"].fillna(age_median)

0    25.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [26]:
age_median
# Raw value

25.0

In [27]:
mode=df["City"].mode()
mode
# series covert to array use values method

0    Pune
Name: City, dtype: object

In [28]:
mode.values[0]

'Pune'

**KNN Imputere**

- K -Nearest Neighbours

- where k = hyper parameter which means the user can change

- idea :Instead of taking all the samples average 

    - First Fix the neighbour number ie k 

    - Then find the nieghbours using the distance metric 

    - Then take the average of those samepls to fill the missing values

In [ ]:
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer

In [36]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
X = [[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
pd.DataFrame(X)

     0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [35]:
imputer=KNNImputer(n_neighbors=2,weights="uniform")
imputer.fit_transform(X)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])

In [37]:
imputer=KNNImputer(n_neighbors=2,weights="distance")
imputer.fit_transform(X)

array([[ 1.        ,  2.        ,  3.93905505],
       [ 3.        , 31.        ,  3.        ],
       [ 3.25775362, 60.        ,  5.        ],
       [ 8.        ,  8.        ,  7.        ]])